### ISSUE TITLE
choosing aonther month or year doesnt work

### ISSUE THREAD

**Issue by user1233** [Shmulik-Kravitz/react-jewish-datepicker#1]
when i choosing another month or year is changing only the day but not the month and year.

even in the demo  - https://react-jewish-datepicker.js.org/

**Comment by Shmulik-Kravitz** [comment]
Hi user123.3,

Thank you for finding the bug and a special thanks for reporting it.

I have fixed it, added tests and published a new version 1.0.5.

Thank you and have a good day
Shmulik
