### ISSUE TITLE
two issues

### ISSUE THREAD

**Issue by yochanan-sheinberger** [Shmulik-Kravitz/react-jewish-datepicker#12]
1. when clicking outside the date picker it does not close. you have to pick a date or click on the picked date. it's annoying.
2.  when changing the value using setState etc. the picked date does not update correspondingly:
this code works. bot when i update greg with setGreg there is no effect on the date picker.
` const [greg, setGreg] = useState(date.greg());`

`<ReactJewishDatePicker
   value={greg}
   isHebrew
   onClick={(day) => {
     handleDatePicker(day);
   }}
/>`

**Comment by Shmulik-Kravitz** [comment]
Fixed in version 1.0.19
