### ISSUE TITLE
not able to install it directly from github

### ISSUE THREAD

**Issue by SalishKumar** [Shmulik-Kravitz/react-jewish-datepicker#28]
i have forked this repo to customize it but when i try to install using npm i faced error so when i tried to install original repo with npm i faced same issue
command: npm i https://github.com/Shmulik-Kravitz/react-jewish-datepicker/tarball/master
error: npm ERR! Cannot read properties of undefined (reading 'spec')

**Comment by Shmulik-Kravitz** [comment]
Hi Salish,

This repo uses yarn workspaces, you will need to build it locally before you can use it.

Thank you and have a good day
Shmulik
